apiVersion: v1
kind: Pod
metadata:
  name: simple-postgres
  #namespace: <accountname>
spec:
  containers:
    - name: postgres-container
      image: postgres
      resources:
        limits:
          memory: '128Mi'
          cpu: '500m'
      ports:
        - containerPort: 5432
      env:
        - name: 'POSTGRES_USER'
          value: 'kube'
        - name: 'POSTGRES_PASSWORD'
          value: 'lesson'
        - name: 'POSTGRES_DB'
          value: 'kube-lesson'
